package https.hom_infoconv_receita_fazenda_gov_br.ws.cpf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-16T16:25:03.450-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", name = "ConsultarCPFSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarCPFSoap {

    /**
     * Consultar Teste CPF - Perfil 3
     */
    @WebMethod(operationName = "ConsultarCPFP3T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP3T")
    @RequestWrapper(localName = "ConsultarCPFP3T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3T")
    @ResponseWrapper(localName = "ConsultarCPFP3TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3TResponse")
    @WebResult(name = "ConsultarCPFP3TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil3 consultarCPFP3T(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil Dinâmico
     */
    @WebMethod(operationName = "ConsultarCPFPD", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFPD")
    @RequestWrapper(localName = "ConsultarCPFPD", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFPD")
    @ResponseWrapper(localName = "ConsultarCPFPDResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFPDResponse")
    @WebResult(name = "ConsultarCPFPDResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfilD consultarCPFPD(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 1A - Com dados Dados ARPEN
     */
    @WebMethod(operationName = "ConsultarCPFP1A", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP1A")
    @RequestWrapper(localName = "ConsultarCPFP1A", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1A")
    @ResponseWrapper(localName = "ConsultarCPFP1AResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1AResponse")
    @WebResult(name = "ConsultarCPFP1AResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil1A consultarCPFP1A(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar Teste CPF - Perfil 1
     */
    @WebMethod(operationName = "ConsultarCPFP1T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP1T")
    @RequestWrapper(localName = "ConsultarCPFP1T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1T")
    @ResponseWrapper(localName = "ConsultarCPFP1TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1TResponse")
    @WebResult(name = "ConsultarCPFP1TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil1 consultarCPFP1T(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar Teste CPF - Perfil 2
     */
    @WebMethod(operationName = "ConsultarCPFP2T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP2T")
    @RequestWrapper(localName = "ConsultarCPFP2T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2T")
    @ResponseWrapper(localName = "ConsultarCPFP2TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2TResponse")
    @WebResult(name = "ConsultarCPFP2TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil2 consultarCPFP2T(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 2A - Com dados Dados ARPEN
     */
    @WebMethod(operationName = "ConsultarCPFP2A", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP2A")
    @RequestWrapper(localName = "ConsultarCPFP2A", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2A")
    @ResponseWrapper(localName = "ConsultarCPFP2AResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2AResponse")
    @WebResult(name = "ConsultarCPFP2AResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil2A consultarCPFP2A(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 3A - Com dados Dados ARPEN
     */
    @WebMethod(operationName = "ConsultarCPFP3A", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP3A")
    @RequestWrapper(localName = "ConsultarCPFP3A", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3A")
    @ResponseWrapper(localName = "ConsultarCPFP3AResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3AResponse")
    @WebResult(name = "ConsultarCPFP3AResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil3A consultarCPFP3A(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil Dinâmico 2 - Com dados Dados ARPEN
     */
    @WebMethod(operationName = "ConsultarCPFPD2", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFPD2")
    @RequestWrapper(localName = "ConsultarCPFPD2", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFPD2")
    @ResponseWrapper(localName = "ConsultarCPFPD2Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFPD2Response")
    @WebResult(name = "ConsultarCPFPD2Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfilD2 consultarCPFPD2(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 1
     */
    @WebMethod(operationName = "ConsultarCPFP1", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP1")
    @RequestWrapper(localName = "ConsultarCPFP1", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1")
    @ResponseWrapper(localName = "ConsultarCPFP1Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP1Response")
    @WebResult(name = "ConsultarCPFP1Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil1 consultarCPFP1(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 2
     */
    @WebMethod(operationName = "ConsultarCPFP2", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP2")
    @RequestWrapper(localName = "ConsultarCPFP2", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2")
    @ResponseWrapper(localName = "ConsultarCPFP2Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP2Response")
    @WebResult(name = "ConsultarCPFP2Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil2 consultarCPFP2(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 3
     */
    @WebMethod(operationName = "ConsultarCPFP3", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/ConsultarCPFP3")
    @RequestWrapper(localName = "ConsultarCPFP3", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3")
    @ResponseWrapper(localName = "ConsultarCPFP3Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ConsultarCPFP3Response")
    @WebResult(name = "ConsultarCPFP3Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cpf.ArrayOfPessoaPerfil3 consultarCPFP3(

        @WebParam(name = "ListaDeCPF", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cpf/")
        java.lang.String cpfUsuario
    );
}
