package https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-16T16:25:03.679-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", name = "ConsultarCNPJSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarCNPJSoap {

    /**
     * Consultar CNPJ - Perfil 3
     */
    @WebMethod(operationName = "ConsultarCNPJP3", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP3")
    @RequestWrapper(localName = "ConsultarCNPJP3", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP3")
    @ResponseWrapper(localName = "ConsultarCNPJP3Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP3Response")
    @WebResult(name = "ConsultarCNPJP3Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil3 consultarCNPJP3(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CNPJ - Perfil 2
     */
    @WebMethod(operationName = "ConsultarCNPJP2", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP2")
    @RequestWrapper(localName = "ConsultarCNPJP2", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP2")
    @ResponseWrapper(localName = "ConsultarCNPJP2Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP2Response")
    @WebResult(name = "ConsultarCNPJP2Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil2 consultarCNPJP2(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar Teste CNPJ - Perfil 2
     */
    @WebMethod(operationName = "ConsultarCNPJP2T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP2T")
    @RequestWrapper(localName = "ConsultarCNPJP2T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP2T")
    @ResponseWrapper(localName = "ConsultarCNPJP2TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP2TResponse")
    @WebResult(name = "ConsultarCNPJP2TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil2 consultarCNPJP2T(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar Teste CNPJ - Perfil 1
     */
    @WebMethod(operationName = "ConsultarCNPJP1T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP1T")
    @RequestWrapper(localName = "ConsultarCNPJP1T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP1T")
    @ResponseWrapper(localName = "ConsultarCNPJP1TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP1TResponse")
    @WebResult(name = "ConsultarCNPJP1TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil1 consultarCNPJP1T(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CNPJ - Perfil 1
     */
    @WebMethod(operationName = "ConsultarCNPJP1", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP1")
    @RequestWrapper(localName = "ConsultarCNPJP1", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP1")
    @ResponseWrapper(localName = "ConsultarCNPJP1Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP1Response")
    @WebResult(name = "ConsultarCNPJP1Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil1 consultarCNPJP1(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar Teste CNPJ - Perfil 3
     */
    @WebMethod(operationName = "ConsultarCNPJP3T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP3T")
    @RequestWrapper(localName = "ConsultarCNPJP3T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP3T")
    @ResponseWrapper(localName = "ConsultarCNPJP3TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ConsultarCNPJP3TResponse")
    @WebResult(name = "ConsultarCNPJP3TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    public https.hom_infoconv_receita_fazenda_gov_br.ws.cnpj.ArrayOfCNPJPerfil3 consultarCNPJP3T(

        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );
}
